-- Migration 001: the generator running-time strip on the Tabulation report.
--
-- The report prints how many minutes the site's generator ran on each of the
-- last seven days, latest first. The figure is read off the generator's own
-- hour meter and typed in by the analyst — there is no telemetry for it, and
-- this table is the only place it exists.
--
-- Why a table at all, when every other manual field on that report (weather,
-- fog, rainfall) lives only in the composed document: those three describe the
-- day being reported and are written once, into that day's PDF. This one is a
-- SEVEN-DAY HISTORY. Yesterday's figure has to still be there tomorrow, or the
-- analyst retypes a week of numbers every morning and a typo in any of them is
-- undetectable. One row per day, entered once, read back into six of the seven
-- columns from then on.
--
-- Keyed by RADAR, not by wall folder and not by site:
--   * a generator powers a radar unit, and re-aiming that radar at a new wall
--     starts a new wall folder — keying to the folder would drop the history on
--     a day when nothing about the generator changed;
--   * a site can run several radars, each on its own generator, and they do not
--     share a running time.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) The readings.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS generator_runtime (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  radar_id    bigint NOT NULL REFERENCES radars (id) ON DELETE CASCADE,

  -- The day the generator RAN, on the SITE's calendar — not the day the figure
  -- was typed. The report is issued at 05:00–06:00 site time, so the entry made
  -- this morning is filed against yesterday. See utils/generatorRuntime.ts,
  -- which builds the window the same way; the two must not disagree about which
  -- date a column stands for.
  run_date    date NOT NULL,

  -- Minutes. 0 is a real reading — the generator did not run that day — and is
  -- deliberately storable; a day with NO figure has no row at all rather than a
  -- zero, so the report can tell "did not run" from "not answered yet".
  minutes     integer NOT NULL CHECK (minutes >= 0 AND minutes <= 1440),

  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- One reading per radar per day. This is also the conflict target the app
-- upserts on (onConflict: 'radar_id,run_date'), so correcting a figure updates
-- the day rather than appending a second answer for it.
CREATE UNIQUE INDEX IF NOT EXISTS generator_runtime_radar_day_key
  ON generator_runtime (radar_id, run_date);

-- The report's only query: the seven days before the report day, newest first.
CREATE INDEX IF NOT EXISTS generator_runtime_radar_recent_idx
  ON generator_runtime (radar_id, run_date DESC);

COMMENT ON TABLE generator_runtime IS
  'Daily generator running time in minutes, one row per radar per day, typed by '
  'the analyst while composing the Tabulation report. Read back as the report''s '
  'seven-day strip; see utils/generatorRuntime.ts.';

COMMENT ON COLUMN generator_runtime.run_date IS
  'The day the generator ran, on the SITE calendar. The report is composed the '
  'following morning, so the entry made on day D is filed against D-1.';

-- ---------------------------------------------------------------------------
-- 2) Keep updated_at honest.
--
-- The strip is entered under time pressure at 05:00 and corrected later; the
-- only way to tell a figure that was revised from one that was right first time
-- is for the row to say so.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION generator_runtime_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS generator_runtime_touch_trg ON generator_runtime;
CREATE TRIGGER generator_runtime_touch_trg
  BEFORE UPDATE ON generator_runtime
  FOR EACH ROW EXECUTE FUNCTION generator_runtime_touch();

-- ---------------------------------------------------------------------------
-- 3) RLS — authenticated reads AND writes.
--
-- Written from the BROWSER, by the signed-in analyst composing the report, the
-- same way monitoring_areas is written from the Add Sensor modal. A read-only
-- policy would leave the strip permanently blank.
--
-- Drop this section if `radars` runs with RLS disabled on your project — the
-- two tables should be governed alike.
-- ---------------------------------------------------------------------------
ALTER TABLE generator_runtime ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS generator_runtime_read ON generator_runtime;
CREATE POLICY generator_runtime_read ON generator_runtime
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS generator_runtime_write ON generator_runtime;
CREATE POLICY generator_runtime_write ON generator_runtime
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
