-- Migration 001: TARP documents, triggers, contacts and revision history.
--
-- Replaces the hard-coded TARP mapping (config/formConfig.ts TYPE_MATRIX) and the
-- hard-coded document (components/Home/TarpComponent.tsx) with per-site rows.
--
-- The key idea: ONE table (tarp_triggers) carries both the presentation columns
-- (what the client's TARP chart prints) and the engine columns (def_type,
-- tarp_level, requires_alarm). The email subject a client receives is therefore
-- generated from the exact row printed in their own TARP document.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) Documents — one row per site per version.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tarp_documents (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id          bigint NOT NULL REFERENCES clients (id) ON DELETE CASCADE,

  -- Sheet 1 header block
  heading          text,          -- "Genesis Minerals" / "Greatland Gold - Telfer Open Pit"
  title            text NOT NULL DEFAULT 'Radar - Trigger Action Response Plan Chart',
  response_owner   text NOT NULL DEFAULT 'Primary Trigger Response - DTG Engineer',

  -- Version control
  version          integer NOT NULL DEFAULT 1,
  status           text    NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft', 'active', 'superseded')),
  effective_from   date,

  -- Free-text blocks that sit under the chart
  footer_note      text,          -- "ALL CALLS FROM REMOTE ENGINEER … EMAIL SUMMARY"
  escalation_note  text,          -- "contact hierarchy: 1. supervisor 2. superintendent …"
  distribution_raw text,          -- Genesis keeps its mailing list as one free-text cell

  created_at       timestamptz NOT NULL DEFAULT now(),
  created_by       uuid,
  updated_at       timestamptz NOT NULL DEFAULT now(),

  UNIQUE (site_id, version)
);

-- At most one live document per site.
CREATE UNIQUE INDEX IF NOT EXISTS tarp_documents_one_active
  ON tarp_documents (site_id)
  WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- 2) Triggers — one row per line of the TARP chart.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tarp_triggers (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id    bigint  NOT NULL REFERENCES tarp_documents (id) ON DELETE CASCADE,
  sort_order     integer NOT NULL,

  -- --- Presentation (what the chart prints) ---
  risk_rating    text,           -- Extreme | Moderate | Intermediate | NULL
  band_label     text,           -- "TARP Trigger 4 - Red"   (Genesis col B)
  trigger_label  text NOT NULL,  -- "Progressive (accelerating) trend"
  colour         text,           -- red | orange | yellow | grey | green
  description    text,
  day_shift      text,
  night_shift    text,
  comments       jsonb NOT NULL DEFAULT '[]'::jsonb,  -- ordered array of strings
  extra_note     text,           -- Genesis col H ("After calling supervisor … ")

  -- --- Engine (what drives the email subject) ---
  -- def_type matches config/formConfig.ts TYPE_MATRIX keys: 'Progressive',
  -- 'Linear Accelerating', 'Linear', 'Regressive', 'Failure', 'Blast Event', …
  -- NULL means this row is descriptive only (alarm rows, connection rows).
  def_type         text,
  tarp_level       smallint CHECK (tarp_level BETWEEN 0 AND 4),
  requires_alarm   boolean NOT NULL DEFAULT false,
  -- Optional override for the subject bracket. NULL = derive from tarp_level.
  severity_bracket text,

  UNIQUE (document_id, sort_order)
);

CREATE INDEX IF NOT EXISTS tarp_triggers_document_idx
  ON tarp_triggers (document_id);

-- A deformation type may map to at most one trigger row per document,
-- otherwise the engine has no deterministic answer.
CREATE UNIQUE INDEX IF NOT EXISTS tarp_triggers_def_type_uq
  ON tarp_triggers (document_id, def_type)
  WHERE def_type IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3) Contacts — escalation hierarchy + email distribution list.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tarp_contacts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id bigint  NOT NULL REFERENCES tarp_documents (id) ON DELETE CASCADE,
  kind        text    NOT NULL DEFAULT 'escalation'
                CHECK (kind IN ('escalation', 'distribution')),
  sort_order  integer NOT NULL,
  name        text,
  role        text,
  phone       text,
  email       text,

  UNIQUE (document_id, kind, sort_order)
);

CREATE INDEX IF NOT EXISTS tarp_contacts_document_idx
  ON tarp_contacts (document_id);

-- ---------------------------------------------------------------------------
-- 4) Revisions — the "TARP History" / "DOCUMENT CONTROL" sheet.
--    Kept against the document so the audit trail travels with the export.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tarp_revisions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       bigint  NOT NULL REFERENCES tarp_documents (id) ON DELETE CASCADE,
  seq               integer NOT NULL,  -- the "No." column
  site_label        text,              -- "Leonora - Genesis Minerals"
  version_no        integer,
  approval_date     date,
  approved_by_site  text,
  site_role         text,
  approved_by_dtg   text,              -- header reads "GSS" on some sites
  dtg_role          text,
  modified_date     date,
  sections_modified text,
  remark            text,

  UNIQUE (document_id, seq)
);

CREATE INDEX IF NOT EXISTS tarp_revisions_document_idx
  ON tarp_revisions (document_id);

-- ---------------------------------------------------------------------------
-- 5) Keep updated_at honest.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION tarp_documents_touch() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tarp_documents_touch_trg ON tarp_documents;
CREATE TRIGGER tarp_documents_touch_trg
  BEFORE UPDATE ON tarp_documents
  FOR EACH ROW EXECUTE FUNCTION tarp_documents_touch();

-- ---------------------------------------------------------------------------
-- 6) OPTIONAL — row level security.
--    Only run this block if your other tables also run with RLS enabled and the
--    dashboard talks to Supabase with an authenticated session. Enabling RLS on
--    a project whose client uses the anon key without a session will make the
--    TARP tab come back empty.
-- ---------------------------------------------------------------------------
-- ALTER TABLE tarp_documents ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tarp_triggers  ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tarp_contacts  ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE tarp_revisions ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY tarp_documents_rw ON tarp_documents
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- CREATE POLICY tarp_triggers_rw  ON tarp_triggers
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- CREATE POLICY tarp_contacts_rw  ON tarp_contacts
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- CREATE POLICY tarp_revisions_rw ON tarp_revisions
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
