-- Migration 001: the monitoring-area roster behind the Tabulation report.
--
-- The Tabulation report's movement table lists one row per ACTIVE DEFORMATION
-- CHAIN. That is the right table for an SSR/MSR wall: an area with nothing
-- moving has no active record, so it has no row, and the table is exactly the
-- list of things the site has to act on.
--
-- A PS radar is monitored the other way round. Its client is handed a fixed set
-- of monitoring points and expects to read EVERY one of them every day —
-- including the ones sitting quietly at TARP 1 — because the absence of a row
-- is not evidence the point was checked. There is no way to express that today:
-- nothing "lowers" a record back to TARP 1 (the analyst archives it instead,
-- isactive = 'No'), and a calm area therefore vanishes from the report.
--
-- Two objects, and deliberately no new def_records semantics:
--
--   monitoring_areas          the roster — the points that exist on a wall,
--                             whether or not anything is happening on them
--   radars.movement_table_style   which of the two tables this radar prints
--
-- What is NOT done here, and why: a "No Significant" row in def_records would
-- have been the smaller migration, and it would have been wrong. That record
-- would flow into resolveRiskPresentation as a risk driver, into the
-- Comprehensive report's chain timeline, into the email engine's severity
-- bracket (which reads tarp_level) and into the Area Analysis gate — five
-- places that would then have to filter it back out. The roster keeps calm
-- areas as PRESENTATION and leaves the risk rollup exactly as it is.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) The roster.
--
-- Keyed by WALL FOLDER, not by radar: the roster is a property of the wall
-- being scanned, and a radar re-aimed at a new wall is monitoring different
-- points. `def_records.location` is scoped the same way, which is what makes
-- the report's join between the two well defined.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS monitoring_areas (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallfolder_id  bigint NOT NULL REFERENCES radar_wall_folders (id) ON DELETE CASCADE,

  -- Matched against def_records.location, case- and whitespace-insensitively
  -- (see areaKey in utils/dailyStatusRows.js). Stored as the analyst typed it,
  -- because this is also what the report PRINTS in the Area column.
  name           text NOT NULL,

  -- The order the client reads their own points in. The report sorts by
  -- severity first and falls back to this, so a calm day prints the site's own
  -- sequence rather than an alphabetical one they do not recognise.
  sort_order     integer NOT NULL DEFAULT 0,

  -- 'Yes' / 'No', spelled as def_records.isactive spells it rather than as a
  -- boolean, so the two tables are read the same way in the same query file.
  -- A retired point stops printing without losing the history filed against it.
  isactive       text NOT NULL DEFAULT 'Yes',

  created_at     timestamptz NOT NULL DEFAULT now()
);

-- One row per point per wall. The uniqueness is on the MATCH key, not the
-- printed name: 'Kaki disp 1' and 'Kaki Disp 1' are one point, and allowing
-- both would print the same area twice forever.
CREATE UNIQUE INDEX IF NOT EXISTS monitoring_areas_wallfolder_name_key
  ON monitoring_areas (wallfolder_id, lower(btrim(name)));

CREATE INDEX IF NOT EXISTS monitoring_areas_wallfolder_idx
  ON monitoring_areas (wallfolder_id, sort_order, id);

COMMENT ON TABLE monitoring_areas IS
  'The monitoring points that exist on a wall folder, whether or not anything '
  'is moving on them. Read by the Tabulation report when the radar''s '
  'movement_table_style is ''roster''; see config/movementTableStyle.ts.';

-- ---------------------------------------------------------------------------
-- 2) Which table a radar prints.
--
-- NULL means "no explicit choice" and the app falls back to the radar FAMILY
-- default resolved from radar_number (PS -> roster, everything else -> chain,
-- see classifyRadar in config/radarParameterSets.ts). That is what makes a new
-- PS radar correct on the day it is commissioned without anyone remembering to
-- set a flag, while leaving every existing SSR/MSR radar untouched.
--
-- NOT a site-level setting: one site can run a PS alongside an SSR, and they do
-- not report the same way.
-- ---------------------------------------------------------------------------
ALTER TABLE radars
  ADD COLUMN IF NOT EXISTS movement_table_style text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'radars_movement_table_style_chk'
  ) THEN
    ALTER TABLE radars
      ADD CONSTRAINT radars_movement_table_style_chk
      CHECK (movement_table_style IS NULL
             OR movement_table_style IN ('chain', 'roster'));
  END IF;
END $$;

COMMENT ON COLUMN radars.movement_table_style IS
  '''chain'' (the DTG standard): one movement-table row per active deformation '
  'chain. ''roster'': one row per monitoring_areas entry, calm points included. '
  'NULL falls back to the radar family default. See config/movementTableStyle.ts.';

-- ---------------------------------------------------------------------------
-- 3) Seed the roster for the radars that will print it.
--
-- Every location ever filed against the wall folder, archived records included:
-- a point that has been quiet for a month is still a point, and the whole
-- purpose of the roster is that it does not disappear when nothing is moving.
--
-- DISTINCT ON the match key rather than on `location`, so two spellings of one
-- point seed one row (the unique index above would reject the second anyway).
--
-- Scoped to PS radars because those are the ones whose default resolves to
-- 'roster'. Widening it later is another INSERT; seeding a wall that prints the
-- chain table would create rows nothing reads.
-- ---------------------------------------------------------------------------
INSERT INTO monitoring_areas (wallfolder_id, name, sort_order)
SELECT
  seed.wallfolder_id,
  seed.name,
  row_number() OVER (PARTITION BY seed.wallfolder_id ORDER BY lower(seed.name))
FROM (
  SELECT DISTINCT ON (d.wallfolder_id, lower(btrim(d.location)))
    d.wallfolder_id,
    btrim(d.location) AS name
  FROM def_records d
  JOIN radar_wall_folders wf ON wf.id = d.wallfolder_id
  JOIN radars r              ON r.id  = wf.radar_id
  WHERE d.location IS NOT NULL
    AND btrim(d.location) <> ''
    AND COALESCE(r.movement_table_style, CASE WHEN r.radar_number ILIKE 'ps%'
                                              THEN 'roster' ELSE 'chain' END) = 'roster'
  ORDER BY d.wallfolder_id, lower(btrim(d.location)), d.created_at
) AS seed
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- 4) RLS — authenticated reads AND writes.
--
-- Unlike weather_readings, this table is written from the BROWSER: the Add
-- Sensor modal seeds the roster with the same signed-in client that inserts the
-- radar and its wall folder, so a read-only policy would fail commissioning.
-- Every surface that touches it sits behind the admin login.
--
-- Drop this section if `radars` and `radar_wall_folders` run with RLS disabled
-- on your project — a roster that is invisible to the report is worse than one
-- that is merely unprotected, and the two tables should be governed alike.
-- ---------------------------------------------------------------------------
ALTER TABLE monitoring_areas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS monitoring_areas_read ON monitoring_areas;
CREATE POLICY monitoring_areas_read ON monitoring_areas
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS monitoring_areas_write ON monitoring_areas;
CREATE POLICY monitoring_areas_write ON monitoring_areas
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- 5) Note for whoever maintains latest_radar_wall_folders.
--
-- The app resolves the style from radar_number when the view does not expose
-- movement_table_style, so nothing here is required for the feature to work.
-- Adding `r.movement_table_style` to that view is what makes a PER-RADAR
-- override (as opposed to the family default) take effect on the report —
-- resolveMovementTableStyle reads it first when it is present.
-- ---------------------------------------------------------------------------
