-- Migration 001: weather stations, readings, fog assessments, poll audit.
--
-- Context: the Ambient Weather public endpoint
-- (https://lightning.ambientweather.net/devices/{mac}) returns CURRENT
-- CONDITIONS ONLY. There is no history endpoint. Every table here exists
-- because history has to be accumulated by polling and persisted — that is the
-- single constraint the whole feature is built around.
--
-- weather_readings is therefore the irreplaceable asset: if a poll is missed,
-- that minute is gone forever and cannot be back-filled from anywhere.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) Stations — one row per Ambient Weather station bound to a site.
--
-- `clients` is this platform's site table (id, site_name, latitude, longitude,
-- timezone). The station's own coordinates are stored separately and are the
-- ones the solar-position maths must use: the station can sit kilometres from
-- the pit it is reporting for, and the fog index is computed at the sensor.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weather_stations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id       bigint NOT NULL REFERENCES clients (id) ON DELETE CASCADE,

  -- The MAC is the natural key everywhere downstream; readings and assessments
  -- reference it rather than the surrogate id so a re-bind never orphans data.
  mac_address   text NOT NULL UNIQUE,
  name          text,

  latitude      double precision NOT NULL,
  longitude     double precision NOT NULL,

  -- Not reported by the endpoint. Inferable from absolute pressure: ASBSAR1
  -- reads 26.639 inHg = 902 hPa, which puts it near 950 m. Operator-entered.
  elevation_m   double precision,

  -- Great-circle km from the bound site, snapshot at bind time. Kept so the
  -- station list can be ordered without recomputing against a moving site.
  distance_km   double precision,

  -- The station's OWN IANA zone, from the `tz` field of its response
  -- ("Asia/Singapore" for ASBSAR1). This is what `dailyrainin` resets against,
  -- so rainfall bucketing MUST use it and not the site's timezone.
  timezone      text NOT NULL DEFAULT 'UTC',

  station_type  text,             -- e.g. "AMBWeatherPro_V5.1.1"
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- One bound station per site. The read APIs (/api/sites/[id]/weather etc.)
-- resolve "the site's station" with no tie-break, so the constraint is what
-- makes that resolution well defined. Mirrors tarp_documents_one_active.
CREATE UNIQUE INDEX IF NOT EXISTS weather_stations_one_active_per_site
  ON weather_stations (site_id)
  WHERE is_active;

CREATE INDEX IF NOT EXISTS weather_stations_site_idx
  ON weather_stations (site_id);

-- ---------------------------------------------------------------------------
-- 2) Readings — the accumulated history. Append-only, upserted on every poll.
--
-- Everything the scoring function needs is stored pre-derived in SI, because
-- re-deriving on read means re-running solar geometry over 288 rows per chart.
-- `raw` keeps the scalar-only original so a derivation bug can be repaired
-- without the data being lost.
--
-- Rain stays in mm here even though the endpoint speaks inches: the imperial
-- values are preserved verbatim inside `raw`, and every consumer of this table
-- wants metric. Conversion happens once, at ingest.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS weather_readings (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mac_address        text NOT NULL REFERENCES weather_stations (mac_address)
                       ON UPDATE CASCADE ON DELETE CASCADE,

  -- From `dateutc` (epoch ms). The station's clock, not the poller's.
  observed_at        timestamptz NOT NULL,

  -- --- Core thermodynamics (SI) ---
  temp_c             double precision,
  dew_point_c        double precision,
  -- Stored, not computed on read: it is the single most queried quantity and
  -- every gate/threshold in the index keys off it.
  --
  -- NOTE: dew point is derived server-side by Ambient from tempf + humidity.
  -- dpd_c and humidity are therefore NOT independent signals. Nothing in the
  -- scoring may treat them as two pieces of corroborating evidence.
  dpd_c              double precision,
  humidity           double precision,

  -- --- Wind (km/h) ---
  -- Prefers windspdmph_avg10m over windspeedmph when the station reports it;
  -- the 10-minute average is what the 2-7 km/h optimal band was defined on.
  wind_kmh           double precision,
  wind_gust_kmh      double precision,
  wind_dir           double precision,

  -- --- Radiation ---
  solar_wm2          double precision,
  uv                 double precision,

  -- --- Pressure (hPa) ---
  -- From baromrelin. On stations whose owner never set a sea-level offset
  -- (ASBSAR1 among them) this is absolute pressure. Only the 3-hour DELTA is
  -- scored, so the missing offset is harmless — but do not display it as MSLP.
  pressure_hpa       double precision,

  -- --- Rain (mm) ---
  -- rain_rate_mmh comes from `hourlyrainin`, which is a RATE in inches/hour,
  -- NOT an accumulation. Summing it over time is wrong. It answers exactly one
  -- question: "is it raining right now". Hourly totals are derived from deltas
  -- of rain_daily_mm — see migration 002.
  rain_rate_mmh      double precision,
  rain_daily_mm      double precision,
  rain_weekly_mm     double precision,
  rain_monthly_mm    double precision,
  rain_yearly_mm     double precision,
  rain_event_mm      double precision,

  -- --- Solar geometry, computed at ingest from the STATION's lat/lon ---
  solar_elevation_deg double precision,
  ghi_clear_wm2       double precision,   -- Haurwitz clear-sky GHI
  -- solar_wm2 / ghi_clear_wm2, only when ghi_clear_wm2 > 20. May exceed 1.0
  -- under cloud-edge enhancement; that is expected and must not be clamped.
  clearness_index     double precision,

  raw                jsonb,
  created_at         timestamptz NOT NULL DEFAULT now(),

  -- The station reports on its own cadence and the 5-minute poll will re-read
  -- the same observation more than once. This constraint plus ON CONFLICT is
  -- what makes the poll idempotent.
  CONSTRAINT weather_readings_mac_observed_key UNIQUE (mac_address, observed_at)
);

-- Every read path is "latest N for one station", in this exact order.
CREATE INDEX IF NOT EXISTS weather_readings_mac_observed_desc_idx
  ON weather_readings (mac_address, observed_at DESC);

-- ---------------------------------------------------------------------------
-- 3) Fog assessments — the calibration record. Never pruned.
--
-- The thresholds in the algorithm are literature defaults, not values
-- calibrated against this valley. Recalibration means re-scoring history under
-- new constants and comparing, so each row records the constants it was scored
-- under and the per-component breakdown that produced the total. Without
-- `constants` a re-score is not comparable to the original.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fog_assessments (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mac_address       text NOT NULL REFERENCES weather_stations (mac_address)
                      ON UPDATE CASCADE ON DELETE CASCADE,

  -- The instant scored FOR (the newest reading's timestamp), not the instant
  -- the scorer ran. Re-scoring history must land on the same assessed_at.
  assessed_at       timestamptz NOT NULL,

  -- NULL only when verdict = 'INSUFFICIENT_HISTORY'.
  score_a           integer CHECK (score_a IS NULL OR score_a BETWEEN 0 AND 100),

  verdict           text NOT NULL CHECK (verdict IN (
                      'FOG',                  -- Index B confirmed
                      'FOG_LIKELY',           -- Index A >= 70
                      'AMBIGUOUS',            -- Index A 45-69
                      'NOT_FOG',              -- Index B: low stratus / overcast
                      'NO_FOG',               -- gate fired, or below threshold
                      'INSUFFICIENT_HISTORY'  -- < 8 readings in window
                    )),
  reason            text,

  -- [{component, points, max, detail, available}] — points earned vs available
  -- per component, and whether the component had enough data to mean anything.
  components        jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- [{gate, detail}] — empty array when nothing vetoed.
  gates             jsonb NOT NULL DEFAULT '[]'::jsonb,

  minutes_saturated double precision,
  dt_dt             double precision,   -- degC/hour, signed
  kt_peak           double precision,   -- max daytime clearness over 24 h

  history_hours     numeric(6,2),
  reading_count     integer,
  -- False at night and on stations with no pyranometer. The UI must say so
  -- rather than silently showing a score that was never cross-checked.
  index_b_available boolean NOT NULL DEFAULT false,

  -- The tuning constants this row was scored under (DPD_SAT, WIND_LO/HI/VETO,
  -- component tables). Makes a re-score under new constants comparable.
  constants         jsonb,
  algorithm_version text NOT NULL DEFAULT '1',

  created_at        timestamptz NOT NULL DEFAULT now(),

  -- Re-running the poll in the same minute must not duplicate the record.
  CONSTRAINT fog_assessments_mac_assessed_key UNIQUE (mac_address, assessed_at)
);

CREATE INDEX IF NOT EXISTS fog_assessments_mac_assessed_desc_idx
  ON fog_assessments (mac_address, assessed_at DESC);

-- ---------------------------------------------------------------------------
-- 4) Poll runs — audit trail for the cron.
--
-- A silent poller is the failure mode that matters: readings simply stop, the
-- UI keeps rendering the last row, and nobody notices until the fog index is
-- scoring against yesterday's air.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS poll_runs (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at         timestamptz NOT NULL DEFAULT now(),
  finished_at        timestamptz,
  stations_attempted integer NOT NULL DEFAULT 0,
  stations_succeeded integer NOT NULL DEFAULT 0,
  stations_failed    integer NOT NULL DEFAULT 0,
  readings_inserted  integer NOT NULL DEFAULT 0,
  -- [{mac, error}] — capped by the route so one broken station cannot bloat
  -- the table.
  error_samples      jsonb NOT NULL DEFAULT '[]'::jsonb,
  trigger_source     text                 -- 'cron' | 'manual' | 'backfill'
);

CREATE INDEX IF NOT EXISTS poll_runs_started_desc_idx
  ON poll_runs (started_at DESC);

-- ---------------------------------------------------------------------------
-- 5) updated_at trigger for weather_stations
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_weather_stations_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS weather_stations_updated_at ON weather_stations;
CREATE TRIGGER weather_stations_updated_at
  BEFORE UPDATE ON weather_stations
  FOR EACH ROW EXECUTE FUNCTION set_weather_stations_updated_at();

-- ---------------------------------------------------------------------------
-- 6) RLS — authenticated reads, service-role writes.
--
-- The service role bypasses RLS entirely, so "writes only by the service role"
-- is expressed by the ABSENCE of any INSERT/UPDATE/DELETE policy. Adding a
-- write policy for `authenticated` would be the bug, not the fix. The poll
-- route uses lib/supaBaseServer.js, which holds the service key.
-- ---------------------------------------------------------------------------
ALTER TABLE weather_stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE weather_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE fog_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_runs       ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS weather_stations_read ON weather_stations;
CREATE POLICY weather_stations_read ON weather_stations
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS weather_readings_read ON weather_readings;
CREATE POLICY weather_readings_read ON weather_readings
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS fog_assessments_read ON fog_assessments;
CREATE POLICY fog_assessments_read ON fog_assessments
  FOR SELECT TO authenticated USING (true);

-- poll_runs is operational telemetry; readable so the UI can show poll health.
DROP POLICY IF EXISTS poll_runs_read ON poll_runs;
CREATE POLICY poll_runs_read ON poll_runs
  FOR SELECT TO authenticated USING (true);

-- ---------------------------------------------------------------------------
-- 7) Retention.
--
-- weather_readings: 90 days. It is a 5-minute series — ~26k rows per station
-- per quarter — and nothing downstream reads past 24 h except a re-score.
-- fog_assessments: kept forever. It IS the calibration record; pruning it
-- destroys the only evidence of how the thresholds behaved over a wet season.
-- poll_runs: 30 days, purely operational.
--
-- NOTE the ordering constraint this creates: a re-score of readings older than
-- 90 days is impossible. If you plan a recalibration campaign, archive
-- weather_readings before the window closes.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION prune_weather_history()
RETURNS TABLE (readings_deleted bigint, poll_runs_deleted bigint)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r bigint;
  p bigint;
BEGIN
  DELETE FROM weather_readings WHERE observed_at < now() - interval '90 days';
  GET DIAGNOSTICS r = ROW_COUNT;

  DELETE FROM poll_runs WHERE started_at < now() - interval '30 days';
  GET DIAGNOSTICS p = ROW_COUNT;

  RETURN QUERY SELECT r, p;
END;
$$;

REVOKE ALL ON FUNCTION prune_weather_history() FROM public, anon, authenticated;

-- Schedule it if pg_cron is available. On Supabase, enable the extension under
-- Database > Extensions first; this block is a no-op when it is absent so the
-- migration stays runnable on a plain Postgres.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('prune-weather-history')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prune-weather-history');
    PERFORM cron.schedule('prune-weather-history', '17 3 * * *',
                          'SELECT prune_weather_history()');
  ELSE
    RAISE NOTICE 'pg_cron not installed — run prune_weather_history() from a scheduled job instead.';
  END IF;
END;
$$;
