import React from 'react';
import { X, Download, Mail, Printer, Calendar, User, Building } from 'lucide-react';
import { Button } from "@/components/LandingPage/ui/button";

interface ReportTemplateProps {
  type: 'alarm' | 'data-quality' | 'availability' | 'safety';
  onClose: () => void;
  children: React.ReactNode;
}

const getReportConfig = (type: string) => {
  switch (type) {
    case 'alarm':
      return {
        title: 'Alarm Summary Report',
        subtitle: 'Comprehensive Alarm Analysis & Trends',
        color: '#f97316',
        bgGradient: 'from-red-500/10 to-orange-500/10'
      };
    case 'data-quality':
      return {
        title: 'Data Quality Report',
        subtitle: 'Quality Metrics & Performance Analysis',
        color: '#14b8a6',
        bgGradient: 'from-teal-500/10 to-blue-500/10'
      };
    case 'availability':
      return {
        title: 'System Availability Report',
        subtitle: 'Uptime & Reliability Metrics',
        color: '#10b981',
        bgGradient: 'from-green-500/10 to-emerald-500/10'
      };
    case 'safety':
      return {
        title: 'Safety Inspection Report',
        subtitle: 'Workplace Safety Compliance Summary',
        color: '#eab308',
        bgGradient: 'from-yellow-500/10 to-amber-500/10'
      };
    default:
      return {
        title: 'Report',
        subtitle: 'Generated Report',
        color: '#14b8a6',
        bgGradient: 'from-teal-500/10 to-blue-500/10'
      };
  }
};

export function ReportTemplate({ type, onClose, children }: ReportTemplateProps) {
  const config = getReportConfig(type);
  const today = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return (
    <div className="fixed inset-0 bg-[var(--dtg-bg-primary)]/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-[var(--dtg-bg-primary)] rounded-xl shadow-2xl w-full max-w-6xl max-h-[90vh] overflow-hidden flex flex-col border border-[var(--dtg-border-medium)]">
        {/* Header */}
        <div className={`bg-gradient-to-r ${config.bgGradient} border-b border-[var(--dtg-border-medium)] p-6`}>
          <div className="flex items-start justify-between mb-4">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <div 
                  className="w-2 h-12 rounded-full" 
                  style={{ backgroundColor: config.color }}
                />
                <div>
                  <h1 className="text-3xl text-[var(--dtg-text-primary)]">{config.title}</h1>
                  <p className="text-[var(--dtg-gray-500)] text-sm mt-1">{config.subtitle}</p>
                </div>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 hover:bg-white/10 rounded-lg transition-all"
            >
              <X className="w-6 h-6 text-[var(--dtg-gray-500)] hover:text-[var(--dtg-text-primary)]" />
            </button>
          </div>

          {/* Report Metadata */}
          <div className="grid grid-cols-4 gap-4">
            <div className="bg-[var(--dtg-bg-card)]/50 rounded-lg p-3 border border-[var(--dtg-border-medium)]">
              <div className="flex items-center gap-2 text-[var(--dtg-gray-500)] text-sm mb-1">
                <Calendar className="w-4 h-4" />
                <span>Report Date</span>
              </div>
              <p className="text-[var(--dtg-text-primary)] text-sm">{today}</p>
            </div>
            <div className="bg-[var(--dtg-bg-card)]/50 rounded-lg p-3 border border-[var(--dtg-border-medium)]">
              <div className="flex items-center gap-2 text-[var(--dtg-gray-500)] text-sm mb-1">
                <User className="w-4 h-4" />
                <span>Generated By</span>
              </div>
              <p className="text-[var(--dtg-text-primary)] text-sm">ABC Operator</p>
            </div>
            <div className="bg-[var(--dtg-bg-card)]/50 rounded-lg p-3 border border-[var(--dtg-border-medium)]">
              <div className="flex items-center gap-2 text-[var(--dtg-gray-500)] text-sm mb-1">
                <Building className="w-4 h-4" />
                <span>Location</span>
              </div>
              <p className="text-[var(--dtg-text-primary)] text-sm">ABC Mine Site</p>
            </div>
            <div className="bg-[var(--dtg-bg-card)]/50 rounded-lg p-3 border border-[var(--dtg-border-medium)]">
              <div className="flex items-center gap-2 text-[var(--dtg-gray-500)] text-sm mb-1">
                <Calendar className="w-4 h-4" />
                <span>Period</span>
              </div>
              <p className="text-[var(--dtg-text-primary)] text-sm">Last 30 Days</p>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="flex-1 overflow-y-auto p-6 bg-[var(--dtg-bg-primary)]">
          <div className="max-w-5xl mx-auto space-y-6">
            {children}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="border-t border-[var(--dtg-border-medium)] p-4 bg-[var(--dtg-bg-card)]/50">
          <div className="flex items-center justify-between">
            <div className="text-sm text-[var(--dtg-gray-500)]">
              <span>Document ID: RPT-{type.toUpperCase()}-{Date.now().toString().slice(-6)}</span>
            </div>
            <div className="flex items-center gap-3">
              <Button
                variant="outline">
                <Printer className="w-4 h-4 mr-2" />
                Print
              </Button>
              <Button
                variant="outline">
                <Mail className="w-4 h-4 mr-2" />
                Email
              </Button>
              <Button
                variant="brand"
              >
                <Download className="w-4 h-4 mr-2" />
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
