-- Migration 001: per-site report layouts.
--
-- WHY THIS TABLE EXISTS
--
-- The Tabulation and Comprehensive radar reports are assembled from measured
-- blocks, and the order of those blocks was the source code: one `out.push(...)`
-- sequence per template. So every time a client asked for something the report
-- did not already print — Hidden Valley's per-radar rainfall summary being the
-- one that prompted this — the answer was a new block component, a new push,
-- and a site check somewhere to decide who saw it. Each of those branches lands
-- in a template that every OTHER client also renders, and the templates were on
-- their way to being a pile of per-site conditionals.
--
-- A layout row moves that decision out of the code. It records, for one site and
-- one report category:
--
--   * which of the report's DEFAULT sections print, and in what order
--   * any CUSTOM sections the site has asked for — a table, a paragraph, or an
--     image slot — interleaved with the defaults in the same list
--
-- Adding a client with an unusual report is then a row, edited in the report
-- generator's config pane. Nothing here is site-aware; see config/reportSections.ts
-- for the default catalogue and utils/reportLayout.js for the payload shape.
--
-- WHAT IS AND IS NOT IN `sections`
--
-- STRUCTURE only, by default: column headings, row counts, section titles,
-- order. NOT this morning's readings. A layout that carried the values would
-- reprint them under tomorrow's date, and nothing on the printed page would say
-- they were yesterday's — a stale number in a client report is worse than a
-- blank one. The analyst can fold the cells they have filled in into the saved
-- structure explicitly (that is how "SSR777XT" becomes part of the layout while
-- "30.38 mm" does not), and pasted IMAGES are never saved at any setting: they
-- are data URLs, and a report figure is evidence for one report.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) The table.
--
-- Keyed by (site, category) and not by radar. A layout describes the DOCUMENT a
-- client receives, and a site that runs four radars sends one report format for
-- all of them — where a per-radar difference exists it is already expressed as
-- a property of the radar (radars.movement_table_style), not as a different
-- document.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS report_layouts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  site_id     bigint NOT NULL REFERENCES clients (id) ON DELETE CASCADE,

  -- The report category as the generator names it: 'Tabulation' (the daily
  -- report) or 'Comprehensive'. Stored as the same string the UI switches on,
  -- so there is no second vocabulary to keep in step. Deliberately unconstrained
  -- by an enum — a category the code does not recognise is ignored by the
  -- loader, which is the failure mode we want when a row outlives a rename.
  category    text NOT NULL,

  -- { version, entries: [...] } — see utils/reportLayout.js. A NULL or damaged
  -- payload is not an error: normalizeLayout falls back to the default order,
  -- so a bad row degrades to the report the site was getting before.
  sections    jsonb NOT NULL DEFAULT '{"version":1,"entries":[]}'::jsonb,

  updated_at  timestamptz NOT NULL DEFAULT now(),

  -- Who last changed the shape of a client's report. Free text, matching how
  -- `reports.generated_by` is written elsewhere in the generator.
  updated_by  text
);

-- One layout per site per category. The editor upserts on this, so a double
-- click on Save cannot leave two layouts fighting over the same report.
CREATE UNIQUE INDEX IF NOT EXISTS report_layouts_site_category_idx
  ON report_layouts (site_id, category);

-- ---------------------------------------------------------------------------
-- 2) Keep updated_at honest.
--
-- The editor could send it, but then a client written by hand in the SQL editor
-- would not, and "when did this site's report last change shape" is the first
-- question asked when a report comes out looking unfamiliar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION report_layouts_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS report_layouts_touch ON report_layouts;
CREATE TRIGGER report_layouts_touch
  BEFORE UPDATE ON report_layouts
  FOR EACH ROW EXECUTE FUNCTION report_layouts_touch();

-- ---------------------------------------------------------------------------
-- 3) RLS.
--
-- Mirrors monitoring_areas and radar_scan_georef: every surface that reaches
-- this table sits behind the admin login, and the same signed-in user both
-- edits a layout and reads it back when generating the report, so a read-only
-- policy would break the editor outright.
--
-- Drop this section if `clients` runs with RLS disabled on your project — the
-- two should be governed alike.
-- ---------------------------------------------------------------------------
ALTER TABLE report_layouts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS report_layouts_read ON report_layouts;
CREATE POLICY report_layouts_read ON report_layouts
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS report_layouts_write ON report_layouts;
CREATE POLICY report_layouts_write ON report_layouts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- 4) No backfill.
--
-- A site with no row gets the default order, which is exactly the report it
-- receives today. Seeding every client with an explicit copy of the current
-- order would freeze them against future changes to the templates: a section
-- added to the Tabulation report next year would be inserted into a site with
-- no row automatically, but a seeded row would say nothing about it and the
-- normaliser would have to guess where it goes.
-- ---------------------------------------------------------------------------
