export const PARAMETER_CONFIG = {
    "Data Availability": ["Optimal", "Critical"],
    "SSR Type & Scan Mode": ["Optimal", "Sub-Optimal"],
    "Signal Strength (Amplitude)": ["Optimal", "Critical"],
    "Scan Area": ["Optimal", "Critical"],
    "Vector Loss": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Coherence": ["Optimal", "Acceptable", "Sub-Optimal", "Critical"],
    "Image Alignment": ["Optimal", "Sub-Optimal", "Critical"],
    "Camera Alignment": ["Optimal", "Sub-Optimal"],
    "Photo Quality": ["Optimal", "Sub-Optimal", "Critical"],
    "Sky and Short Range Masks": ["Optimal", "Sub-Optimal", "Critical"],
    "Enhanced Deformation Mask": ["Optimal", "Acceptable", "Sub-Optimal", "Critical"],
    "Alarm Settings and Notifications": ["Optimal", "Sub-Optimal", "Critical"],
    "Global and Alarm Masks": ["Optimal", "Acceptable", "Sub-Optimal", "Critical"],
    "Atmospheric Correction Source": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Dynamic Stable Reference Areas": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Stable Reference Area Spread": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Atmospheric Refractivity": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Atmospheric Correction Graph": ["Optimal", "Acceptable", "Sub-Optimal"],
    "Geo-Positioning": ["Optimal", "Acceptable", "Sub-Optimal"],
    "3D-DTM": ["Optimal", "Acceptable", "Sub-Optimal"],
};