-- ===========================================================================
-- radar_scan_georef — where a wall folder's radar scans sit on the mine grid.
--
-- Safe to run repeatedly in the Supabase SQL Editor.
--
-- Background
-- ----------
-- A slope-monitoring radar export carries Easting/Northing/Elevation columns,
-- but they are RADAR-LOCAL metres: the origin is the sensor head, which is why
-- `Range (m)` equals hypot(E, N, Elevation) exactly in every file. The scan's
-- internal geometry is therefore already correct to the millimetre; only its
-- POSE — where the sensor stood and which way it looked — is approximate.
--
-- So what is stored here is a rigid-body transform (rotation + translation,
-- scale locked at 1), solved once from hand-placed tie points, and nothing
-- else about the scan. The CSVs themselves are never uploaded: they are large,
-- they are regenerated every few hours, and the operator already has them. One
-- transform per wall folder is the small, durable part worth sharing, and it
-- is what lets the NEXT scan of the same folder place itself with no work.
--
-- Keyed by WALL FOLDER rather than by scan, for the same reason
-- monitoring_areas is: the pose belongs to the wall being watched and to the
-- sensor watching it, not to one seven-hour observation window.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS radar_scan_georef (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- The identity parsed out of the filename: everything before the trailing
  -- _DDMMYYYY_HHMM_DDMMYYYY_HHMM window, e.g.
  --   SSR535_260808_HVM_HVK7_East_Wall-1
  -- This is the authoritative key. It is what the tool has in hand the instant
  -- a file is dropped, before any database lookup, so auto-apply never waits on
  -- a join resolving.
  scan_key       text NOT NULL,

  -- The resolved wall folder, when one exists. Nullable on purpose: a radar can
  -- be exporting scans before its folder has been commissioned in the platform,
  -- and refusing to store the georeference until the paperwork catches up would
  -- lose real work. Backfill it later; scan_key keeps working either way.
  wallfolder_id  bigint REFERENCES radar_wall_folders (id) ON DELETE SET NULL,

  -- Decomposed from scan_key so the row is legible on its own and can be
  -- reconciled against radars / radar_wall_folders without re-parsing.
  radar_number   text,                    -- radars.radar_number, e.g. SSR535
  folder_name    text,                    -- radar_wall_folders.name
  commenced      text,                    -- folder commencement, YYMMDD as written

  -- 'yaw'   rotation about the vertical only — a levelled sensor, 2+ ties
  -- 'rigid' full 3-D rotation — sensor on a slope, 3+ non-collinear ties
  mode           text NOT NULL DEFAULT 'yaw' CHECK (mode IN ('yaw', 'rigid')),

  -- Row-major 3x3 rotation and the translation, in mine-grid metres.
  -- Stored as plain float arrays rather than a PostGIS type: this is a sensor
  -- pose, not a geometry, and nothing here is ever spatially queried in SQL.
  -- Because the source frame's origin IS the sensor head, `t` is literally the
  -- radar's surveyed position — which is the number to eyeball when a fit
  -- looks wrong.
  r              double precision[] NOT NULL CHECK (array_length(r, 1) = 9),
  t              double precision[] NOT NULL CHECK (array_length(t, 1) = 3),

  -- Fit quality, kept so the next person can judge the pose without redoing it.
  rms            double precision,
  bearing_deg    double precision,
  tilt_deg       double precision,

  -- The tie points that produced the transform: [{src, dst, px, py, label}].
  -- Kept so a georeference can be REOPENED and one bad point corrected, rather
  -- than every point being re-placed to fix one.
  ties           jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- A coarse range image of the footprint (angular bounds + a downsampled
  -- range grid, a few kB). This is what lets an operator who has no CSVs on
  -- their machine still click the pit and be told which wall folders watch
  -- that spot. It is an approximation and the app treats it as one — whenever
  -- the real scan is loaded, the exact test overrules it.
  footprint      jsonb,

  -- Scan windows seen for this folder: [{filename, startAt, endAt}], newest
  -- first, capped by the app. Because the CSVs stay local, this is the only
  -- record of WHICH scans exist, and it is what the "sorted by date, latest on
  -- top" list is built from on a machine that has none of them.
  scans          jsonb NOT NULL DEFAULT '[]'::jsonb,

  created_by     uuid,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- One pose per wall folder. The upsert in the app targets this constraint, so
-- re-georeferencing corrects the existing row instead of layering a second
-- pose that later reads would have to arbitrate between.
CREATE UNIQUE INDEX IF NOT EXISTS radar_scan_georef_key_uidx
  ON radar_scan_georef (scan_key);

CREATE INDEX IF NOT EXISTS radar_scan_georef_wallfolder_idx
  ON radar_scan_georef (wallfolder_id);

CREATE INDEX IF NOT EXISTS radar_scan_georef_radar_idx
  ON radar_scan_georef (radar_number);

COMMENT ON TABLE radar_scan_georef IS
  'Rigid-body pose placing a radar wall folder''s scans on the mine grid, '
  'solved from hand-placed tie points in the Sensitivity Tools 3-D view. '
  'One row per wall folder; the scan CSVs themselves are never stored.';

-- ---------------------------------------------------------------------------
-- updated_at
--
-- Re-georeferencing is the interesting event on this table — it means someone
-- decided the old pose was wrong — so the timestamp is maintained in the
-- database rather than trusted to the client that is correcting it.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION radar_scan_georef_touch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS radar_scan_georef_touch_trg ON radar_scan_georef;
CREATE TRIGGER radar_scan_georef_touch_trg
  BEFORE UPDATE ON radar_scan_georef
  FOR EACH ROW EXECUTE FUNCTION radar_scan_georef_touch();

-- ---------------------------------------------------------------------------
-- Row level security
--
-- Mirrors monitoring_areas: every surface that reaches this table sits behind
-- the admin login, and the same signed-in user both registers a wall folder
-- and reads it back, so a read-only policy would break registration outright.
--
-- Drop this section if `radars` and `radar_wall_folders` run with RLS disabled
-- on your project — the three should be governed alike.
-- ---------------------------------------------------------------------------
ALTER TABLE radar_scan_georef ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS radar_scan_georef_read ON radar_scan_georef;
CREATE POLICY radar_scan_georef_read ON radar_scan_georef
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS radar_scan_georef_write ON radar_scan_georef;
CREATE POLICY radar_scan_georef_write ON radar_scan_georef
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ---------------------------------------------------------------------------
-- Backfilling wallfolder_id
--
-- scan_key decomposes as <radar_number>_<YYMMDD>_<folder name>, which is
-- exactly radars.radar_number + radar_wall_folders.commenced_at + .name. Run
-- this after commissioning catches up; it only fills rows that are still null,
-- so it is safe to re-run.
-- ---------------------------------------------------------------------------
UPDATE radar_scan_georef g
   SET wallfolder_id = w.id
  FROM radar_wall_folders w
  JOIN radars ra ON ra.id = w.radar_id
 WHERE g.wallfolder_id IS NULL
   AND ra.radar_number = g.radar_number
   AND lower(btrim(w.name)) = lower(btrim(g.folder_name));
