-- Migration 001: client onboarding flow, contact trials and Supabase-hosted logos.
--
-- The onboarding checklist DTG already runs by email — see the Genesis Minerals
-- thread — becomes state the dashboard owns:
--
--   1. Administration        limitations acknowledged, TARP contacts, sign-off
--   2. Remote connection     TeamViewer Tensor licence + latency check
--   3. Communication trial   trial calls to every TARP contact
--   4. Email trial           test email to the distribution list
--   5. System readiness      radar, wall folder, DQP and alarms configured
--   6. Live commencement     the notice that monitoring has started
--
-- Onboarding belongs to the SITE, not the radar: the acknowledgement, the
-- contacts and the connection are agreed once with the client, and a second
-- radar dropped onto a live site inherits them. `clients` is that grain.
--
-- Idempotent. Safe to run repeatedly in the Supabase SQL Editor.

-- ---------------------------------------------------------------------------
-- 1) One onboarding per site.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client_onboardings (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id       bigint NOT NULL UNIQUE REFERENCES clients (id) ON DELETE CASCADE,

  status        text NOT NULL DEFAULT 'in_progress'
                  CHECK (status IN ('in_progress', 'complete')),

  -- The date the formal monitoring service started. Set when the live
  -- commencement notice goes out, and the only thing the tab gate reads
  -- besides the step rows.
  commenced_at  timestamptz,

  started_at    timestamptz NOT NULL DEFAULT now(),
  completed_at  timestamptz,
  notes         text,

  created_by    uuid,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2) The steps. One row per checklist line per site.
--
--    `payload` is deliberately jsonb: what "done" means differs per step (a
--    latency figure, a meeting time, a list of documents sent) and none of it is
--    queried across sites. The shape each step keeps is documented in
--    config/onboarding.ts, which is the only writer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS onboarding_steps (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onboarding_id  bigint NOT NULL REFERENCES client_onboardings (id) ON DELETE CASCADE,

  step_key       text NOT NULL CHECK (step_key IN (
                   'administration',
                   'remote_connection',
                   'communication_trial',
                   'email_trial',
                   'system_readiness',
                   'live_commencement'
                 )),
  sort_order     integer NOT NULL,

  status         text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'in_progress', 'blocked', 'done')),

  -- When the step's email draft was last opened. Not proof of delivery — the
  -- app hands the draft to Outlook and never sends — so it records only that an
  -- engineer got as far as drafting it.
  email_drafted_at timestamptz,

  completed_at   timestamptz,
  completed_by   uuid,
  notes          text,
  payload        jsonb NOT NULL DEFAULT '{}'::jsonb,

  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),

  UNIQUE (onboarding_id, step_key)
);

CREATE INDEX IF NOT EXISTS onboarding_steps_onboarding_idx
  ON onboarding_steps (onboarding_id);

-- ---------------------------------------------------------------------------
-- 3) Contact trials — who answered and who did not.
--
--    A snapshot, not a join: the phone number that was actually dialled is
--    copied onto the row, so a later TARP revision that replaces a contact does
--    not rewrite the history of what was tested. `contact_id` still points at
--    the TARP row where one exists, and goes null if that row is deleted.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS onboarding_contact_tests (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  onboarding_id  bigint NOT NULL REFERENCES client_onboardings (id) ON DELETE CASCADE,

  -- Which trial this result belongs to.
  step_key       text NOT NULL CHECK (step_key IN ('communication_trial', 'email_trial')),
  channel        text NOT NULL CHECK (channel IN ('phone', 'email')),

  contact_id     bigint REFERENCES tarp_contacts (id) ON DELETE SET NULL,

  -- Snapshot of the contact as tested.
  name           text,
  role           text,
  phone          text,
  email          text,
  -- 'day' | 'night' | NULL. The TARP names a day-shift and a night-shift
  -- on-call; a trial that reached one says nothing about the other.
  shift          text CHECK (shift IN ('day', 'night')),

  result         text NOT NULL DEFAULT 'pending'
                   CHECK (result IN ('pending', 'reachable', 'no_answer', 'unreachable', 'wrong_details')),
  tested_at      timestamptz,
  tested_by      uuid,
  remark         text,

  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS onboarding_contact_tests_onboarding_idx
  ON onboarding_contact_tests (onboarding_id, step_key);

-- One result per contact per trial. A retest updates the row rather than
-- appending, so "which contacts are reachable" has one answer per contact.
CREATE UNIQUE INDEX IF NOT EXISTS onboarding_contact_tests_contact_uq
  ON onboarding_contact_tests (onboarding_id, step_key, contact_id)
  WHERE contact_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 4) Logos in Supabase Storage.
--
--    `clients.logo_path` holds a repo-relative path ("../CompanyLogo/LogoOnly/
--    Genesis.png") into public/logo, which means a new client cannot be
--    onboarded without a deploy. These two columns hold OBJECT PATHS inside the
--    'CompanyLogo' bucket instead; utils/companyLogos.ts prefers them and falls
--    back to logo_path so nothing already shipped changes.
--
--      logo_full_path  the full lockup — mark + wordmark. Report mastheads.
--      logo_mark_path  the compact mark alone. Dashboard header, tight spaces.
-- ---------------------------------------------------------------------------
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_full_path text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS logo_mark_path text;

-- Public bucket: a client logo is a masthead asset that html2pdf has to fetch
-- during export, and a signed URL that expires mid-render prints a broken image.
INSERT INTO storage.buckets (id, name, public)
VALUES ('CompanyLogo', 'CompanyLogo', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage policies. Reads are open (the bucket is public anyway); writes are
-- for signed-in engineers only.
DO $$
BEGIN
  BEGIN
    CREATE POLICY company_logo_read ON storage.objects
      FOR SELECT USING (bucket_id = 'CompanyLogo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    CREATE POLICY company_logo_write ON storage.objects
      FOR INSERT TO authenticated WITH CHECK (bucket_id = 'CompanyLogo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    CREATE POLICY company_logo_update ON storage.objects
      FOR UPDATE TO authenticated USING (bucket_id = 'CompanyLogo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    CREATE POLICY company_logo_delete ON storage.objects
      FOR DELETE TO authenticated USING (bucket_id = 'CompanyLogo');
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'Skipped storage.objects policies — run this block as the postgres role.';
END $$;

-- ---------------------------------------------------------------------------
-- 5) Keep updated_at honest.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION onboarding_touch() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS client_onboardings_touch_trg ON client_onboardings;
CREATE TRIGGER client_onboardings_touch_trg
  BEFORE UPDATE ON client_onboardings
  FOR EACH ROW EXECUTE FUNCTION onboarding_touch();

DROP TRIGGER IF EXISTS onboarding_steps_touch_trg ON onboarding_steps;
CREATE TRIGGER onboarding_steps_touch_trg
  BEFORE UPDATE ON onboarding_steps
  FOR EACH ROW EXECUTE FUNCTION onboarding_touch();

DROP TRIGGER IF EXISTS onboarding_contact_tests_touch_trg ON onboarding_contact_tests;
CREATE TRIGGER onboarding_contact_tests_touch_trg
  BEFORE UPDATE ON onboarding_contact_tests
  FOR EACH ROW EXECUTE FUNCTION onboarding_touch();

-- ---------------------------------------------------------------------------
-- 6) BACKFILL — every site that already has a radar is already onboarded.
--
--    This is not cosmetic. SensorDetail shows ONLY the Onboarding tab until a
--    site's onboarding is complete, so without this every existing client would
--    lose Deformation, Alarm, DQP, Downtime and TARP the moment this ships.
--
--    `commenced_at` is taken from the site's earliest radar, which is the date
--    monitoring actually started.
-- ---------------------------------------------------------------------------
INSERT INTO client_onboardings (site_id, status, commenced_at, started_at, completed_at, notes)
SELECT
  c.id,
  'complete',
  MIN(r.commenced_at)::timestamptz,
  COALESCE(MIN(r.commenced_at)::timestamptz, now()),
  COALESCE(MIN(r.commenced_at)::timestamptz, now()),
  'Backfilled: site was live before the onboarding flow existed.'
FROM clients c
JOIN radars r ON r.site_id = c.id
GROUP BY c.id
ON CONFLICT (site_id) DO NOTHING;

-- The step rows for those backfilled onboardings, all marked done.
INSERT INTO onboarding_steps (onboarding_id, step_key, sort_order, status, completed_at, notes)
SELECT
  o.id,
  s.step_key,
  s.sort_order,
  'done',
  o.completed_at,
  'Backfilled with the onboarding.'
FROM client_onboardings o
CROSS JOIN (VALUES
  ('administration',      1),
  ('remote_connection',   2),
  ('communication_trial', 3),
  ('email_trial',         4),
  ('system_readiness',    5),
  ('live_commencement',   6)
) AS s(step_key, sort_order)
WHERE o.status = 'complete'
ON CONFLICT (onboarding_id, step_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 7) OPTIONAL — row level security.
--    Mirrors the note on the TARP schema: only enable these if the rest of the
--    project runs with RLS and an authenticated session, or the onboarding tab
--    will come back empty.
-- ---------------------------------------------------------------------------
-- ALTER TABLE client_onboardings        ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE onboarding_steps          ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE onboarding_contact_tests  ENABLE ROW LEVEL SECURITY;
--
-- CREATE POLICY client_onboardings_rw ON client_onboardings
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- CREATE POLICY onboarding_steps_rw ON onboarding_steps
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- CREATE POLICY onboarding_contact_tests_rw ON onboarding_contact_tests
--   FOR ALL TO authenticated USING (true) WITH CHECK (true);
